
package wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProductsServiceService", targetNamespace = "http://service.enterprise.solovev.xyz/", wsdlLocation = "http://localhost:8080/ProductsService?wsdl")
public class ProductsServiceService
    extends Service
{

    private final static URL PRODUCTSSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException PRODUCTSSERVICESERVICE_EXCEPTION;
    private final static QName PRODUCTSSERVICESERVICE_QNAME = new QName("http://service.enterprise.solovev.xyz/", "ProductsServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ProductsService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRODUCTSSERVICESERVICE_WSDL_LOCATION = url;
        PRODUCTSSERVICESERVICE_EXCEPTION = e;
    }

    public ProductsServiceService() {
        super(__getWsdlLocation(), PRODUCTSSERVICESERVICE_QNAME);
    }

    public ProductsServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRODUCTSSERVICESERVICE_QNAME, features);
    }

    public ProductsServiceService(URL wsdlLocation) {
        super(wsdlLocation, PRODUCTSSERVICESERVICE_QNAME);
    }

    public ProductsServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRODUCTSSERVICESERVICE_QNAME, features);
    }

    public ProductsServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductsServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProductsService
     */
    @WebEndpoint(name = "ProductsServicePort")
    public ProductsService getProductsServicePort() {
        return super.getPort(new QName("http://service.enterprise.solovev.xyz/", "ProductsServicePort"), ProductsService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProductsService
     */
    @WebEndpoint(name = "ProductsServicePort")
    public ProductsService getProductsServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.enterprise.solovev.xyz/", "ProductsServicePort"), ProductsService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRODUCTSSERVICESERVICE_EXCEPTION!= null) {
            throw PRODUCTSSERVICESERVICE_EXCEPTION;
        }
        return PRODUCTSSERVICESERVICE_WSDL_LOCATION;
    }

}
